/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacePetVet;

import javax.swing.JOptionPane;

/**
 *
 * @author CP
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jComboBoxMascota = new javax.swing.JComboBox<>();
        jComboBoxDueno = new javax.swing.JComboBox<>();
        jTextField_Edad = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        jTextField15 = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        jComboBox_PrincipioActivo = new javax.swing.JComboBox<>();
        jComboBox_Medicamento = new javax.swing.JComboBox<>();
        jLabel51 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator26 = new javax.swing.JSeparator();
        jTextField_Resultado = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        jPanel17 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel_Volver = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(55, 56, 77));

        jPanel16.setBackground(new java.awt.Color(55, 56, 77));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel16.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, 10));

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(240, 240, 240));
        jLabel_Titulo.setText("Calculadora");
        jPanel16.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(240, 240, 240));
        jLabel39.setText("Seleccionar Dueño");
        jPanel16.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(240, 240, 240));
        jLabel40.setText("Seleccionar Principio Activo");
        jPanel16.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(240, 240, 240));
        jLabel41.setText("Seleccionar mascota");
        jPanel16.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(240, 240, 240));
        jLabel42.setText("Raza");
        jPanel16.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(240, 240, 240));
        jPanel16.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(240, 240, 240));
        jPanel16.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(240, 240, 240));
        jLabel46.setText("Edad");
        jPanel16.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(240, 240, 240));
        jLabel47.setText("Peso");
        jPanel16.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));
        jPanel16.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 170, 10));
        jPanel16.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 120, 10));

        jComboBoxMascota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel16.add(jComboBoxMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 210, -1));

        jComboBoxDueno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxDueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDuenoActionPerformed(evt);
            }
        });
        jPanel16.add(jComboBoxDueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 210, -1));

        jTextField_Edad.setBackground(jPanel16.getBackground());
        jTextField_Edad.setForeground(new java.awt.Color(240, 240, 240));
        jTextField_Edad.setBorder(null);
        jTextField_Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_EdadActionPerformed(evt);
            }
        });
        jPanel16.add(jTextField_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 210, -1));

        jTextField14.setBackground(jPanel16.getBackground());
        jTextField14.setForeground(new java.awt.Color(240, 240, 240));
        jTextField14.setBorder(null);
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel16.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 210, -1));
        jPanel16.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 210, 5));

        jTextField15.setBackground(jPanel16.getBackground());
        jTextField15.setForeground(new java.awt.Color(240, 240, 240));
        jTextField15.setBorder(null);
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel16.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 210, -1));
        jPanel16.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 210, 10));

        jComboBox_PrincipioActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel16.add(jComboBox_PrincipioActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 160, -1));

        jComboBox_Medicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Medicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_MedicamentoActionPerformed(evt);
            }
        });
        jPanel16.add(jComboBox_Medicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 160, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(240, 240, 240));
        jLabel51.setText("Seleccionar Medicamento");
        jPanel16.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jTextField16.setBackground(jPanel16.getBackground());
        jTextField16.setForeground(new java.awt.Color(240, 240, 240));
        jTextField16.setBorder(null);
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel16.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 210, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jPanel16.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 20));
        jPanel16.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 210, 10));

        jTextField_Resultado.setBackground(jPanel16.getBackground());
        jTextField_Resultado.setForeground(new java.awt.Color(240, 240, 240));
        jTextField_Resultado.setText("Resultado");
        jTextField_Resultado.setBorder(null);
        jPanel16.add(jTextField_Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 210, -1));
        jPanel16.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 210, 5));

        jPanel17.setBackground(new java.awt.Color(0, 153, 102));
        jPanel17.setForeground(new java.awt.Color(240, 240, 240));

        jLabel48.setForeground(new java.awt.Color(240, 240, 240));
        jLabel48.setText("Calcular");
        jPanel17.add(jLabel48);

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 70, 30));

        jPanel4.setBackground(new java.awt.Color(0, 102, 255));
        jPanel4.setForeground(new java.awt.Color(240, 240, 240));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Ayuda");
        jPanel4.add(jLabel6);

        jPanel16.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 70, -1));

        jPanel_Volver.setBackground(new java.awt.Color(153, 51, 255));
        jPanel_Volver.setForeground(new java.awt.Color(240, 240, 240));
        jPanel_Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel_VolverMouseClicked(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Volver");
        jPanel_Volver.add(jLabel12);

        jPanel16.add(jPanel_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 70, -1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        JOptionPane.showMessageDialog(this,"Seleccionar un cliente una mascota y un medicamento y presionar calcular");
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jComboBox_MedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_MedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_MedicamentoActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField_EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_EdadActionPerformed

    private void jComboBoxDuenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDuenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDuenoActionPerformed

    private void jPanel_VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_VolverMouseClicked
        Buscador vBuscar = new Buscador();
        vBuscar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel_VolverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxDueno;
    private javax.swing.JComboBox<String> jComboBoxMascota;
    private javax.swing.JComboBox<String> jComboBox_Medicamento;
    private javax.swing.JComboBox<String> jComboBox_PrincipioActivo;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel_Volver;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField_Edad;
    private javax.swing.JTextField jTextField_Resultado;
    // End of variables declaration//GEN-END:variables
}
